import { useMemo } from 'react'
import { createPortal } from 'react-dom'
import { format } from 'date-fns'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Cell } from 'recharts'
import { ChartContainer } from '@/components/ui/chart'
import { Log } from '@/lib/mock-logs'

interface PrintReportProps {
  logs: Log[]
  userName: string
}

export function PrintReport({ logs, userName }: PrintReportProps) {
  const chartData = useMemo(() => {
    const counts = logs.reduce(
      (acc, log) => {
        acc[log.action] = (acc[log.action] || 0) + 1
        return acc
      },
      {} as Record<string, number>,
    )

    return [
      { action: 'Create', count: counts['Create'] || 0, fill: 'hsl(var(--chart-1))' },
      { action: 'Update', count: counts['Update'] || 0, fill: 'hsl(var(--chart-2))' },
      { action: 'Delete', count: counts['Delete'] || 0, fill: 'hsl(var(--chart-3))' },
      { action: 'Assign', count: counts['Assign'] || 0, fill: 'hsl(var(--chart-4))' },
    ].filter((d) => d.count > 0)
  }, [logs])

  const chartConfig = {
    count: { label: 'Count' },
  }

  const content = (
    <>
      <style type="text/css">
        {`
          @media print {
            body > :not(#print-root) {
              display: none !important;
            }
            #print-root {
              display: block !important;
            }
            @page {
              margin: 1cm;
            }
          }
        `}
      </style>
      <div id="print-root" className="hidden print:block w-full bg-white text-black p-8 font-sans">
        <div className="flex justify-between items-start border-b pb-6 mb-8">
          <div className="flex items-center gap-4">
            <img
              src="https://img.usecurling.com/i?q=company+logo&color=blue&shape=fill"
              alt="Company Logo"
              className="w-16 h-16 object-contain"
            />
            <div>
              <h1 className="text-3xl font-bold text-slate-900">System Audit Report</h1>
              <p className="text-slate-500 mt-1">Detailed history and activity log</p>
            </div>
          </div>
          <div className="text-right text-sm text-slate-600 space-y-1">
            <p>
              <span className="font-semibold">Generated:</span> {format(new Date(), 'PPpp')}
            </p>
            <p>
              <span className="font-semibold">Generated By:</span> {userName}
            </p>
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-xl font-bold mb-4 text-slate-800 border-b pb-2">Activity Summary</h2>
          <div className="h-[300px] w-full max-w-2xl mx-auto rounded-lg p-4 bg-white">
            <ChartContainer config={chartConfig} className="h-full w-full">
              <BarChart data={chartData} margin={{ top: 20, right: 20, bottom: 20, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis
                  dataKey="action"
                  tickLine={false}
                  axisLine={false}
                  tick={{ fill: '#475569' }}
                />
                <YAxis
                  allowDecimals={false}
                  tickLine={false}
                  axisLine={false}
                  tick={{ fill: '#475569' }}
                />
                <Bar dataKey="count" radius={[4, 4, 0, 0]} isAnimationActive={false}>
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.fill} />
                  ))}
                </Bar>
              </BarChart>
            </ChartContainer>
          </div>
        </div>

        <div>
          <h2 className="text-xl font-bold mb-4 text-slate-800 border-b pb-2">Audit Records</h2>
          <table className="w-full text-sm text-left border-collapse">
            <thead>
              <tr className="border-b-2 border-slate-300">
                <th className="py-3 px-4 font-semibold text-slate-800">Date</th>
                <th className="py-3 px-4 font-semibold text-slate-800">Author</th>
                <th className="py-3 px-4 font-semibold text-slate-800">Action</th>
                <th className="py-3 px-4 font-semibold text-slate-800">Entity</th>
                <th className="py-3 px-4 font-semibold text-slate-800">Changes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {logs.map((log) => (
                <tr key={log.id} className="break-inside-avoid">
                  <td className="py-3 px-4 align-top whitespace-nowrap text-slate-600">
                    {format(new Date(log.timestamp), 'dd/MM/yyyy HH:mm')}
                  </td>
                  <td className="py-3 px-4 align-top text-slate-700 font-medium">
                    {log.user.name}
                  </td>
                  <td className="py-3 px-4 align-top text-slate-600">{log.action}</td>
                  <td className="py-3 px-4 align-top">
                    <div className="font-medium text-slate-800">{log.entityName}</div>
                    <div className="text-xs text-slate-500">{log.entityType}</div>
                  </td>
                  <td className="py-3 px-4 align-top">
                    <ul className="space-y-1">
                      {log.changes.map((c, i) => (
                        <li key={i} className="text-xs">
                          <span className="font-semibold text-slate-700">{c.field}:</span>{' '}
                          {c.oldValue && (
                            <span className="line-through text-red-600 mr-1">{c.oldValue}</span>
                          )}
                          {c.oldValue && <span className="text-slate-400 mx-1">→</span>}
                          <span className="text-green-700 font-medium">{c.newValue}</span>
                        </li>
                      ))}
                    </ul>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  )

  if (typeof document === 'undefined') return null
  return createPortal(content, document.body)
}
